import { RefreshCw, WifiOff, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useRegisterSW } from 'virtual:pwa-register/react';

import { Button } from '@bettergov/kapwa/button';

/**
 * Service-worker lifecycle UI.
 *
 * Registers the Workbox service worker generated by vite-plugin-pwa and
 * surfaces two small, dismissible banners:
 *
 * - "Ready to work offline" the first time the app shell finishes precaching.
 * - "A new version is available" when a fresh service worker is waiting.
 *   The visitor chooses when to reload (`registerType: 'prompt'` in
 *   vite.config.ts) so we never swap the app underneath them mid-read.
 */
export function ReloadPrompt() {
  const { t } = useTranslation('common');
  const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegisteredSW(_swUrl, registration) {
      if (!registration) return;
      // Check for a newer build once an hour while the tab stays open —
      // civic data pages tend to be left open for long stretches.
      window.setInterval(
        () => {
          if (navigator.onLine) void registration.update();
        },
        60 * 60 * 1000
      );
    },
  });

  if (!offlineReady && !needRefresh) return null;

  const close = () => {
    setOfflineReady(false);
    setNeedRefresh(false);
  };

  return (
    <div
      role='status'
      aria-live='polite'
      className='bg-kapwa-bg-surface border-kapwa-border-weak fixed right-4 bottom-4 left-4 z-40 flex items-center gap-3 rounded-lg border p-4 shadow-lg sm:left-auto sm:max-w-sm'
    >
      {needRefresh ? (
        <RefreshCw className='text-kapwa-text-brand h-5 w-5 shrink-0' />
      ) : (
        <WifiOff className='text-kapwa-text-muted h-5 w-5 shrink-0' />
      )}
      <p className='text-kapwa-text-strong flex-1 text-sm'>
        {needRefresh ? t('pwa.updateAvailable') : t('pwa.offlineReady')}
      </p>
      {needRefresh && (
        <Button
          variant='primary'
          size='sm'
          onClick={() => void updateServiceWorker(true)}
        >
          {t('pwa.reload')}
        </Button>
      )}
      <button
        type='button'
        onClick={close}
        aria-label={t('pwa.dismiss')}
        className='text-kapwa-text-muted hover:text-kapwa-text-strong rounded p-1'
      >
        <X className='h-4 w-4' />
      </button>
    </div>
  );
}
